version: '3.7'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - "${MAIL_BIND_IP}:25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      - certs:/etc/letsencrypt/live
    environment:
      - HOSTNAME
      - DOMAINNAME
      - CONTAINER_NAME
    env_file:
      - env-mailserver
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
    networks:
      mail:
        aliases:
          # Allow connecting to this service via
          # mailgate mail.leo9000.de via local network
          - mailgate
          - mail.leo9000.de

  cert-companion:
    image: nginx
    restart: always
    environment:
      - VIRTUAL_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    volumes:
      - "./www:/usr/share/nginx/html:ro"
    networks:
      proxy-network:

networks:
  mail:
    name: global-mail-network
  proxy-network:
    name: global-proxy-network
    # not marked as external although it is to avoid a dependency cycle when
    # installing the projects

volumes:
  maildata:
  mailstate:
  maillogs:
  certs:
    external:
      name: frontend-proxy_certs

# vim: tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab

